apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.0.133@sha256:0551eda5c9ad7370a7b85764f11616d944f4a3f7de9ac7e5554cfed5ef58916f

    podSecurityContext:
      supplementalGroups:
        - 65539

    env:
      SONARR__INSTANCE_NAME: Sonarr
      SONARR__PORT: &port 8989
      SONARR__APPLICATION_URL: "https://sonarr.lab.${BASE_DOMAIN}"
      SONARR__LOG_LEVEL: info
      SONARR__POSTGRES_HOST: postgres.core.svc.cluster.local
      SONARR__POSTGRES_MAIN_DB: ${SONARR_MAIN_DB}
      SONARR__POSTGRES_LOG_DB: ${SONARR_LOG_DB}
      SONARR__POSTGRES_USER: postgres
      SONARR__POSTGRES_PASSWORD:
        secretKeyRef:
          name: postgres-creds
          key: postgres-password

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
          cert-manager.io/cluster-issuer: letsencrypt
          hajimari.io/enable: "true"
          hajimari.io/icon: television-box
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
        hosts:
          - host: &sonarr-host "sonarr.lab.${BASE_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *sonarr-host
            secretName: letsencrypt-sonarr

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config

      data:
        enabled: true
        type: nfs
        server: "${NAS_ADDRESS}"
        path: /volume1/Torrents
        mountPath: /data/nas-torrents

    resources:
      requests:
        cpu: 15m
        memory: 268M
      limits:
        memory: 2357M
