apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sonarr
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.0.318@sha256:a14a8991cae8f9ccfa2b110723433c7f5f42f67ac9a1afd07f28fc6424b24f63

    podSecurityContext:
      supplementalGroups:
        - 65539

    env:
      TZ: ${TIMEZONE}
      SONARR__INSTANCE_NAME: Sonarr
      SONARR__PORT: &port 8989
      SONARR__APPLICATION_URL: "https://sonarr.lab.${BASE_DOMAIN}"
      SONARR__LOG_LEVEL: info
      SONARR__POSTGRES_HOST: postgres.core.svc.cluster.local
      SONARR__POSTGRES_MAIN_DB: ${SONARR_MAIN_DB}
      SONARR__POSTGRES_LOG_DB: ${SONARR_LOG_DB}
      SONARR__POSTGRES_USER: postgres
      SONARR__POSTGRES_PASSWORD:
        secretKeyRef:
          name: postgres-creds
          key: postgres-password
      SONARR__API_KEY:
        secretKeyRef:
          name: *app
          key: api-key

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/sonarr/nord.css"></head>';
            sub_filter_once on;
          cert-manager.io/cluster-issuer: letsencrypt
          hajimari.io/enable: "true"
          hajimari.io/icon: television-box
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
        hosts:
          - host: &sonarr-host "sonarr.lab.${BASE_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *sonarr-host
            secretName: letsencrypt-sonarr

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config

      data:
        enabled: true
        type: nfs
        server: "${NAS_HOSTNAME}"
        path: "${TORRENTS_VOLUME}"
        mountPath: /data/nas-torrents

    podAnnotations:
      secret.reloader.stakater.com/reload: *app

    resources:
      requests:
        cpu: 15m
        memory: 268M
      limits:
        memory: 2357M
