kind: Secret
type: Opaque
apiVersion: v1
metadata:
    name: sonarr
    namespace: apps
stringData:
    api-key: ENC[AES256_GCM,data:1birzF7Ov4nGtn3YhGkjpwpOlt8V5d1CnyjCpLr39CE=,iv:A+yKxJSR0uGVX8Zwjwvw4KQ5TRX6I70r6YErIwF5Ijs=,tag:2rG89IYewhbSXB8Hpzc9zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-10T11:08:15Z"
    mac: ENC[AES256_GCM,data:Db85KAGgz8cUvIvQ+bHERhy2hw7cLR17zm4DB/81vO3cjQA6SD8CnS8pdPdjiVVzxnrCN9jDUsU6XRbONwtXOcKt8G6JzBv8eR+9W6A+zSQ5FS9KyHEtQbU2j9r9lIbA135fz4ZVoAS5eJzFt97BW77u1j+6RzVf3o/T1iJbI2I=,iv:sP4qUzP3kWS27mJbRqi+Coqyyq+A8vetzOgkEdJq+dc=,tag:QoSZgDaLPiMvmNSTzgxqqg==,type:str]
    pgp:
        - created_at: "2022-10-10T11:06:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA83EhJxcYAoBAQ//bDT3QGqutC9RwbLAkO4T6+ka13PLVXeO2qgLwE+T8F4W
            w4b33tBEhP4d322qzusTNY3P+BTrHTNoEsL8hqOG8/q4toan/eRaf70vzpdoMb4W
            /7oiY8WkbVHvyue6N/IGXR2q73l2VUCi3FME4hs7j3LOs6qChBaZAV0j23gWrHQ2
            k3rR+4XVxXNed25ftZOdnysq1fd2nmRNyI4y8OZ0Yp657VHlz+2ZFTbdWyw9YF9F
            NHr+jq4ZsPjouD4YzniYMCUWFGjabIy12MydpSsGQ4XNq6QZ7+Bnm6H57Vi5g0Mf
            fFXgMhGtzCDfmBZJoniUoZC/aUG8XR0WlTzk/UFWl7Fo+vXHmeduwQ/xL0+cFjPQ
            x/zJsXoqtQhhSnerCtIJbEMx/JYJ6+yZWZUNIqNU6kcbeFeFMBc3Gs1CMG1bGCru
            GEqruOQmvamLViLyDa3QOcQY9qxcYXyff69mRbicieOyimRFHKKK7f4RFZFPIUS0
            msqHoh2Jgg3iL0AJsz+/0w8aEID1f8ufA7yuRUxDS+STqlzEU8/W7Oe1u7tMD40e
            HzMJpNjZTXhHFtZiqAZuLA2mmxI/h+X/dxZcPbVBT/oijo1dtlXYnY9lSKuy0B99
            iWXkik/WT0rvlYKO4vYyMZ2jnPa3vVVOxIBwuakrsUXihzz0aK8ZD91gpDhLjCHS
            XgFvnSRedIRdBGQWYeWG8iScYR4o/dlOYHfTdF6nr5KPcURvZIkTN63J/7pCNwGp
            LrQlZQcxbVV1Hpwhw0YC72taj9o2MTtBmb64Tr9Z4W1kj/UlddDJkMpY6pkJ1JA=
            =PScC
            -----END PGP MESSAGE-----
          fp: 05FA72D13D58F8D4588BE3FE5606FFB02A5F0984
    encrypted_regex: ((?i)(pass($|word)|claim|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
