apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: apps
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsGroup: ${SQUASH_UID}
            runAsUser: ${SQUASH_UID}
          containers:
            - name: renovate
              image: renovate/renovate:32.213.2@sha256:aa4cde7bdd43fe26ccda371e15efb3ca9f7071d32c5352bfb650438cad061c40
              args:
                - invakid404/home-cluster
              env:
                - name: LOG_LEVEL
                  value: debug
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
                - mountPath: /data/cache
                  name: cache
          restartPolicy: Never
          volumes:
            - name: cache
              persistentVolumeClaim:
                claimName: renovate-cache
