apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: apps
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsGroup: ${SQUASH_UID}
            runAsUser: ${SQUASH_UID}
          containers:
            - name: renovate
              image: renovate/renovate:32.221.0@sha256:48038531b7091e10592f578d964b75103a4cae9af610d87da94ef0801a8303db
              args:
                - invakid404/home-cluster
              env:
                - name: LOG_LEVEL
                  value: debug
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
                - mountPath: /data/cache
                  name: cache
              resources:
                limits:
                  cpu: 0.5
          restartPolicy: Never
          volumes:
            - name: cache
              persistentVolumeClaim:
                claimName: renovate-cache
