apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: apps
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          containers:
            - name: renovate
              image: renovate/renovate:32.222.2@sha256:acc3f337e975e2f716e7ea8896cd52967ab904802d273fe4f866b3403b80c0c0
              command: ["sh"]
              args:
                [
                  "-c",
                  "usermod --uid ${SQUASH_UID} ubuntu && su -p ubuntu -c 'renovate invakid404/home-cluster'",
                ]
              env:
                - name: LOG_LEVEL
                  value: debug
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
                - mountPath: /data/cache
                  name: cache
              resources:
                limits:
                  cpu: 0.5
          restartPolicy: Never
          volumes:
            - name: cache
              persistentVolumeClaim:
                claimName: renovate-cache
