apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: apps
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsGroup: 0
            runAsUser: 0
          containers:
            - name: renovate
              image: renovate/renovate:33.2.2@sha256:88810e17cbc39c026f328b6d32dc17e41357ec6f8766ed5ed90569eb9306f1ba
              command: ["sh"]
              args:
                - "-c"
                - |
                  usermod --uid ${SQUASH_UID} ubuntu

                  cat >> run.sh <<EOS
                  mkdir -p ~/.gnupg

                  # https://stackoverflow.com/a/59170001/9320790
                  cat >> ~/.gnupg/gpg.conf <<EOF
                  use-agent 
                  pinentry-mode loopback
                  EOF

                  cat >> ~/.gnupg/gpg-agent.conf <<EOF
                  allow-loopback-pinentry
                  EOF

                  find ~/.gnupg -type f -exec chmod 600 {} \\;
                  find ~/.gnupg -type d -exec chmod 700 {} \\;

                  echo RELOADAGENT | gpg-connect-agent

                  echo "$${RENOVATE_GIT_PRIVATE_KEY}" | gpg --import -

                  renovate invakid404/home-cluster
                  EOS

                  chmod +x run.sh
                  su -p ubuntu -c ./run.sh
              env:
                - name: LOG_LEVEL
                  value: debug
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
                - mountPath: /data/cache
                  name: cache
              resources:
                limits:
                  cpu: 0.5
          restartPolicy: Never
          volumes:
            - name: cache
              persistentVolumeClaim:
                claimName: renovate-cache
