apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: apps
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsGroup: ${SQUASH_UID}
            runAsUser: ${SQUASH_UID}
          containers:
            - name: renovate
              image: renovate/renovate:32.214.0@sha256:b375b0836747ee34771dc9622e4d69a4a7c7e2be21b90011c5c89f285d8f3017
              args:
                - invakid404/home-cluster
              env:
                - name: LOG_LEVEL
                  value: debug
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
                - mountPath: /data/cache
                  name: cache
          restartPolicy: Never
          volumes:
            - name: cache
              persistentVolumeClaim:
                claimName: renovate-cache
