apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: actions-runner-controller
    namespace: apps
spec:
    interval: 10m0s
    chart:
        spec:
            chart: actions-runner-controller
            version: 0.23.7
            interval: 10m0s
            sourceRef:
                kind: HelmRepository
                name: actions-runner-controller
                namespace: apps
    values:
        authSecret:
            create: ENC[AES256_GCM,data:dLWr6w==,iv:PzjL3T9kMnF3JLCR2NC/GBEBcbw2O2OvV4F7e6UG3oI=,tag:AuBr+trAF9a0S3evWrNLnw==,type:bool]
            github_token: ENC[AES256_GCM,data:Jw3sFy/04Pl9rPykSs85NEpy8raYZ6iZoOSiIcfm5xCvqhlEqhTSsA==,iv:w2I481e6cmpuClQf4NHPKU1u/SfdAiTbcsa5Lvg61bM=,tag:CXTLBB8yRhpAZMaHc+IoGQ==,type:str]
        githubWebhookServer:
            enabled: true
            service:
                type: ClusterIP
                annotations: {}
                ports:
                    - port: 80
                      targetPort: http
                      protocol: TCP
                      name: http
            ingress:
                enabled: true
                ingressClassName: nginx
                annotations:
                    cert-manager.io/cluster-issuer: letsencrypt
                    external-dns.alpha.kubernetes.io/target: ${PUBLIC_IP}
                hosts:
                    - host: arc.lab.${BASE_DOMAIN}
                      paths:
                        - path: /
                          pathType: Prefix
                tls:
                    - hosts:
                        - arc.lab.${BASE_DOMAIN}
                      secretName: letsencrypt-actions-runner-controller-webhook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-16T20:10:17Z"
    mac: ENC[AES256_GCM,data:4Mds7mqXSC8XYUioX4bXGC3KvyndKE7B5VWOL+vR8enuH4S9fxJR1xrVFBhZ6TAPjoO+BtFl7tKhoF01BaNrWWHL06CvXitdLmKPMOs7Iksr1vzp8NOKIMzSgPaDv2tnjIf/s6dN80LpeyGYHLhiPoMiLV6AAxcJHG1iV0dEK+w=,iv:6/ZCRobEBjkF0hzCSuZVhkYHFwYpIUJvIM89EdxZeAQ=,tag:eFvu/x7On6uU9G88+W2pBQ==,type:str]
    pgp:
        - created_at: "2023-04-16T19:55:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA83EhJxcYAoBAQ/+Naj7gcCw7v/5r9lFJnsS/1gK8vD/etSh+7dU8cD839V5
            Av4X5LA7+kIxTXi3sJPpgWP582aSyS09YBhdEFF0Q2ztgTytblyX5azwgpBEGLw0
            e38u99vwMs4xh19RenzdaUqGsOM/VCU29O41LB2MblTjvmXyoYNOLqJY2o4gW5E4
            WyW1y7Meo1e1K/SGL7Zu5CvJhRsWsdMspXA5sstMbxJ1YdxeCpZu/me+n8vagb9b
            f7lE5mio7AZ5wLUyxuW7OsEeAqwe3niGC1BJo8rTS5Uw4t8YuvjMJiUXE+yVbgLV
            oAjBbVtORm9EWfcGfLk/AaxzXC4s3cw94kfLiszaYeRZ9Cds7HzolQ9I+igq5Fmx
            4f5xDjP29ms1SQwyVQB+MdNeeqZFmL5+V/wIllkcbAjJopcS3ZFIZDCODs7zhXIn
            9AX8CY8FMAhvmnZ9dPeMxblhjlTGNECr0cPBYSDyaO2yJ/+nsA5QQpjozEkc9hGX
            VjbZ19riuoJpn7Y8OtrZaQDOaedRJEL2RmXy5aJ1E8/6Vmw0CZfwgZ22KeIDyKbl
            /ps4jW2pc4/1faAP75TmyhEDfdh+HdfaT06HogpDKnSes7gpwCaK7LF3tuWD+hda
            Os2VDJEk0JW7nuYZdpyncHLUPBYNu6BvZBDy3/8p51hfVdrxmVxWtFfhXPCYvC/S
            XgHy4ZCU2ZViQ1MkPjEYQReZorjWqxCbsFbFCVW6U1ymFnspnFLRueTcMAfLWN0o
            aBOqME38V+OURco0nGnuRqIc247AN3N3JdZrZze8sYBhHZfaT5LL7XgpskmyJ9o=
            =4KqV
            -----END PGP MESSAGE-----
          fp: 05FA72D13D58F8D4588BE3FE5606FFB02A5F0984
    encrypted_regex: ((?i)(pass($|word)|claim|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
