apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps
  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: develop@sha256:3430c9f001f06bb56f82c8d795d5a081a313e2f947ddd1e0076a2a7c30a75630
    dnsConfig:
      options:
        - name: ndots
          value: "1"
    env:
      LOG_LEVEL: "info"
      PORT: 80
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${PRIVATE_WHITELIST}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter_once on;
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Overseerr
          gethomepage.dev/description: Request management and media discovery tool
          gethomepage.dev/group: Media Automation
          gethomepage.dev/icon: overseerr.png
        hosts:
          - host: &overseerr-host "overseerr.lab.${BASE_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *overseerr-host
            secretName: letsencrypt-overseerr
    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config
        mountPath: /app/config
    resources:
      requests:
        cpu: 15m
        memory: 226M
      limits:
        memory: 1937M
