apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: apps
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps
  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: develop@sha256:7d64276b06094bd953a5abe246ef94d1ba03a0f5ed5e7461a255cc5434b4662b
    dnsConfig:
      options:
        - name: ndots
          value: "1"
    env:
      LOG_LEVEL: "info"
      PORT: 80
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${PRIVATE_WHITELIST}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter_once on;
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
          hajimari.io/enable: "true"
          hajimari.io/icon: eye
        hosts:
          - host: &overseerr-host "overseerr.lab.${BASE_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *overseerr-host
            secretName: letsencrypt-overseerr
    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config
        mountPath: /app/config
    resources:
      requests:
        cpu: 15m
        memory: 226M
      limits:
        memory: 1937M
