apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      version: 43.2.0
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: apps
      interval: 10m0s
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    namespaceOverride: apps
    alertmanager:
      enabled: false
    prometheus-node-exporter:
      hostRootFsMount:
        enabled: false
    prometheus:
      prometheusSpec:
        retention: 2w
        retentionSize: 45GB
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        podMonitorNamespaceSelector: {}
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 50Gi
              storageClassName: nfs-client
        additionalScrapeConfigs:
          - job_name: node-exporter
            scrape_interval: 30s
            scrape_timeout: 10s
            honor_timestamps: true
            static_configs:
              - targets:
                  - "${NAS_ADDRESS}:9100"
    grafana:
      defaultDashboardsTimezone: ${TIMEZONE}
      admin:
        existingSecret: "grafana-creds"
        userKey: "admin-user"
        passwordKey: "admin-password"
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          hajimari.io/enable: "true"
          hajimari.io/icon: monitor-eye
          hajimari.io/appName: grafana
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
        hosts:
          - &grafana-host grafana.lab.${BASE_DOMAIN}
        tls:
          - hosts:
              - *grafana-host
            secretName: letsencrypt-grafana
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: "default"
              orgId: 1
              folder: ""
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          node-exporter-full:
            gnetId: 1860
            revision: 29
            datasource: Prometheus
          ingress-nginx:
            gnetId: 9614
            revision: 1
            datasource: Prometheus
