apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      version: 40.3.1
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: apps
      interval: 10m0s
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    namespaceOverride: apps
    alertmanager:
      enabled: false
    prometheus-node-exporter:
      hostRootFsMount:
        enabled: false
    prometheus:
      prometheusSpec:
        retention: 24h
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        podMonitorNamespaceSelector: {}
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
    grafana:
      admin:
        existingSecret: "grafana-creds"
        userKey: "admin-user"
        passwordKey: "admin-password"
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          hajimari.io/enable: "true"
          hajimari.io/icon: monitor-eye
          hajimari.io/appName: grafana
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
        hosts:
          - &grafana-host grafana.lab.${BASE_DOMAIN}
        tls:
          - hosts:
              - *grafana-host
            secretName: letsencrypt-grafana
