apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: minio
      version: "14.2.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10

  values:
    auth:
      existingSecret: minio-creds

    persistence:
      enabled: true
      existingClaim: minio-data

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
        nginx.ingress.kubernetes.io/whitelist-source-range: ${PRIVATE_WHITELIST}
        cert-manager.io/cluster-issuer: letsencrypt
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: High Performance Object Storage
        gethomepage.dev/group: Administration
        gethomepage.dev/icon: minio.png
        gethomepage.dev/name: Minio Console
      hostname: &console-host console.minio.lab.${BASE_DOMAIN}
      tls:
        - hosts:
            - *console-host

    apiIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        external-dns.alpha.kubernetes.io/target: "${PUBLIC_IP}"
        cert-manager.io/cluster-issuer: letsencrypt

      hostname: &api-host minio.lab.${BASE_DOMAIN}
      tls:
        - hosts:
            - *api-host
