---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app homepage
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: homepage
      version: 1.2.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: apps

  values:
    image:
      repository: ghcr.io/benphelps/homepage
      pullPolicy: IfNotPresent
      tag: v0.6.28@sha256:5bfe5825ba6714778cdf6fb1d1dd67ee06d7579ac446f9da562f70c78e880c62

    enableRbac: true
    config:
      kubernetes:
        mode: cluster
      settings:
        theme: dark
      widgets:
        - resources:
            backend: kubernetes
            expanded: true
            cpu: true
            memory: true
      bookmarks:
        - Infrastructure:
            - "Synology NAS":
                - abbr: SN
                  href: https://nas.${BASE_DOMAIN}
                  icon: synology-dsm.png
            - "Synology Drive":
                - abbr: SD
                  href: https://nas.${BASE_DOMAIN}/?launchApp=SYNO.SDS.Drive.Application
                  icon: synology-drive.png
      services:

    podAnnotations:
      configmap.reloader.stakater.com/reload: *app

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${PRIVATE_WHITELIST}
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
        hosts:
          - host: &homepage-host "lab.${BASE_DOMAIN}"
            paths:
              - path: /

        tls:
          - hosts:
              - *homepage-host
            secretName: letsencrypt-homepage
