---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app homepage
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: homepage
      version: 1.2.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: apps

  values:
    image:
      repository: ghcr.io/benphelps/homepage
      pullPolicy: IfNotPresent
      tag: v0.6.20@sha256:c1dc64cb9c09b21b8ec36d91d7acdbaf67724c42525dfe2262e7baffcd48dae1

    enableRbac: true
    config:
      kubernetes:
        mode: cluster
      settings:
        theme: dark
      widgets:
        - resources:
            backend: kubernetes
            expanded: true
            cpu: true
            memory: true
      bookmarks:
        - Infrastructure:
            - "Synology NAS":
                - abbr: SN
                  href: https://nas.${BASE_DOMAIN}
                  icon: synology.png
      services:

    podAnnotations:
      configmap.reloader.stakater.com/reload: *app

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${PRIVATE_WHITELIST}
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
        hosts:
          - host: &homepage-host "lab.${BASE_DOMAIN}"
            paths:
              - path: /

        tls:
          - hosts:
              - *homepage-host
            secretName: letsencrypt-homepage
