apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./core/nfs-subdir-external-provisioner
  prune: true
  dependsOn:
    - name: core-base
