apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./core/reloader
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: reloader
      namespace: core
  dependsOn:
    - name: core-base
