apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: synology-csi
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./core/synology-csi
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
    - name: core-base
