apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: synology-csi
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./core/synology-csi
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: synology-csi-controller
      namespace: core
    - apiVersion: apps/v1
      kind: DaemonSet
      name: synology-csi-node
      namespace: core
  dependsOn:
    - name: core-base
