apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: postgresql
      version: "11.9.8"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    fullnameOverride: postgres

    global:
      postgresql:
        auth:
          existingSecret: postgres-creds

    primary:
      initdb:
        scripts:
          init-sonarr-databases: |
            CREATE DATABASE ${SONARR_MAIN_DB} OWNER postgres;
            CREATE DATABASE ${SONARR_LOG_DB} OWNER postgres;
      persistence:
        enabled: true
        existingClaim: postgres-data
      podSecurityContext:
        enabled: true
        fsGroup: ${SQUASH_UID}
      containerSecurityContext:
        enabled: true
        runAsUser: ${SQUASH_UID}
