apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: postgresql
      version: "12.6.5"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    fullnameOverride: postgres

    global:
      postgresql:
        auth:
          existingSecret: postgres-creds

    primary:
      initdb:
        user: postgres
        scripts:
          radarr.sql: |
            CREATE DATABASE "${RADARR_MAIN_DB}" OWNER postgres;
            CREATE DATABASE "${RADARR_LOG_DB}" OWNER postgres;
          radarr-4k.sql: |
            CREATE DATABASE "${RADARR_4K_MAIN_DB}" OWNER postgres;
            CREATE DATABASE "${RADARR_4K_LOG_DB}" OWNER postgres;
          prowlarr.sql: |
            CREATE DATABASE "${PROWLARR_MAIN_DB}" OWNER postgres;
            CREATE DATABASE "${PROWLARR_LOG_DB}" OWNER postgres;
      persistence:
        enabled: true
        existingClaim: postgres-data
      startupProbe:
        enabled: true
        failureThreshold: 60
        periodSeconds: 30
      podSecurityContext:
        enabled: true
        fsGroup: ${SQUASH_UID}
      containerSecurityContext:
        enabled: true
        runAsUser: ${SQUASH_UID}
