apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: postgresql
      version: "11.9.10"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    fullnameOverride: postgres

    global:
      postgresql:
        auth:
          existingSecret: postgres-creds

    primary:
      initdb:
        user: postgres
        scripts:
          radarr.sql: |
            CREATE DATABASE "${RADARR_MAIN_DB}" OWNER postgres;
            CREATE DATABASE "${RADARR_LOG_DB}" OWNER postgres;
          readarr.sql: |
            CREATE DATABASE "${READARR_MAIN_DB}" OWNER postgres;
            CREATE DATABASE "${READARR_LOG_DB}" OWNER postgres;
          prowlarr.sql: |
            CREATE DATABASE "${PROWLARR_MAIN_DB}" OWNER postgres;
            CREATE DATABASE "${PROWLARR_LOG_DB}" OWNER postgres;
      persistence:
        enabled: true
        existingClaim: postgres-data
      podSecurityContext:
        enabled: true
        fsGroup: ${SQUASH_UID}
      containerSecurityContext:
        enabled: true
        runAsUser: ${SQUASH_UID}
