apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: synology-csi-retain
