apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: esphome
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/esphome
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
  dependsOn:
    - name: apps-base
