apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mermaid2svg
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/mermaid2svg
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
  dependsOn:
    - name: apps-base
