apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: overseerr
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/overseerr
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: overseerr
      namespace: apps
  dependsOn:
    - name: apps-base
