apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prometheus-snmp-exporter
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/prometheus-snmp-exporter
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
    - name: kube-prometheus-stack
