apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: recyclarr
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/recyclarr
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
    - name: sonarr
