apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tor
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/tor
  postBuild:
    substitute:
      OR_PORT: "9090"
      PT_PORT: "44321"
  prune: true
  dependsOn:
    - name: apps-base
