apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: ingress-nginx
      version: "4.4.2"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  values:
    controller:
      config:
        use-forwarded-headers: "true"
        log-format-escape-json: "true"
        log-format-upstream:
          '{"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "x_forwarded_for": "$proxy_add_x_forwarded_for", "request_id": "$req_id",
          "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol",
          "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time,"method": "$request_method", "http_referrer": "$http_referer",
          "http_user_agent": "$http_user_agent" }'
      service:
        externalIPs:
          - "${PRIVATE_IP}"
        externalTrafficPolicy: Local
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: "kube-prometheus-stack"
