apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: ingress-nginx
      version: "4.4.2"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  values:
    config:
      use-forwarded-headers: "true"
      enable-real-ip: "true"
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: "kube-prometheus-stack"
