---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chezz
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: ghcr.io/invakid404/chezz
      pullPolicy: IfNotPresent
      tag: 1.0.0@sha256:05f44a1d08e11844f57b6f1fdf59b4bb6bde7415e82283944576d229e90dad1c

    imagePullSecrets:
      - name: docker-config

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${PRIVATE_WHITELIST}
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
        hosts:
          - host: &chezz-host "chezz.lab.${BASE_DOMAIN}"
            paths:
              - path: /

        tls:
          - hosts:
              - *chezz-host
            secretName: letsencrypt-chezz
