---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unpackerr
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: ghcr.io/onedr0p/unpackerr
      tag: 0.11.2@sha256:668f789d8c912950f5419e40b089a04eae7d526467146cb02b2473a31e2af0bf

    env:
      TZ: "${TIMEZONE}"
      UN_SONARR_0_URL: https://sonarr.lab.${BASE_DOMAIN}
      UN_SONARR_0_PATHS_0: /data/nas-torrents/Downloads/Series
      UN_SONARR_0_API_KEY:
        secretKeyRef:
          name: sonarr
          key: api-key
      UN_RADARR_0_URL: https://radarr.lab.${BASE_DOMAIN}
      UN_RADARR_0_PATHS_0: /data/nas-torrents/Downloads/Movies
      UN_RADARR_0_API_KEY:
        secretKeyRef:
          name: radarr
          key: api-key
      UN_RADARR_1_URL: https://radarr-4k.lab.${BASE_DOMAIN}
      UN_RADARR_1_PATHS_0: "/data/nas-torrents/Downloads/Movies (4K)"
      UN_RADARR_1_API_KEY:
        secretKeyRef:
          name: radarr-4k
          key: api-key

    service:
      main:
        enabled: false

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    podSecurityContext:
      runAsUser: ${SQUASH_UID}
      runAsGroup: ${SQUASH_UID}
      fsGroup: ${SQUASH_UID}

    persistence:
      data:
        enabled: true
        type: nfs
        server: "${NAS_HOSTNAME}"
        path: "${TORRENTS_VOLUME}"
        mountPath: /data/nas-torrents

    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 1000Mi
