apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  BASE_DOMAIN: invak.id
  NAS_ADDRESS: nas
  PUBLIC_IP: 188.124.94.153
  PRIVATE_IP: 100.75.51.26
  SQUASH_UID: "1024"

  TORRENTS_VOLUME: "/volume1/Torrents"

  RADARR_MAIN_DB: radarr-main
  RADARR_LOG_DB: radarr-log

  READARR_MAIN_DB: readarr-main
  READARR_LOG_DB: readarr-log

  PROWLARR_MAIN_DB: prowlarr-main
  PROWLARR_LOG_DB: prowlarr-log
