apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  TIMEZONE: "Europe/Sofia"

  BASE_DOMAIN: invak.id
  NAS_ADDRESS: nas
  PUBLIC_IP: invakid404.asuscomm.com
  PRIVATE_IP: 100.75.51.26
  SQUASH_UID: "1024"

  TORRENTS_VOLUME: "/volume1/Torrents"

  RADARR_MAIN_DB: radarr-main
  RADARR_LOG_DB: radarr-log

  RADARR_4K_MAIN_DB: radarr-4k-main
  RADARR_4K_LOG_DB: radarr-4k-log

  PROWLARR_MAIN_DB: prowlarr-main
  PROWLARR_LOG_DB: prowlarr-log
