apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  TIMEZONE: "Europe/Sofia"

  BASE_DOMAIN: invak.id
  TAILSCALE_DOMAIN: qilin-qilin.ts.net

  NAS_HOSTNAME: nas
  NAS_ADDRESS: 192.168.50.86
  PUBLIC_IP: home.invak.id
  PRIVATE_IP: 192.168.50.128
  PRIVATE_WHITELIST: 100.64.0.0/10,10.42.0.0/16
  SQUASH_UID: "1024"

  ROUTER_IP: 192.168.50.1

  ADGUARD_IP: 192.168.50.129
  QBITTORRENT_IP: 192.168.50.130
  TOR_IP: 192.168.50.131

  TORRENTS_VOLUME: "/volume1/Torrents"

  SONARR_MAIN_DB: sonarr-main
  SONARR_LOG_DB: sonarr-log

  RADARR_MAIN_DB: radarr-main
  RADARR_LOG_DB: radarr-log

  RADARR_4K_MAIN_DB: radarr-4k-main
  RADARR_4K_LOG_DB: radarr-4k-log

  PROWLARR_MAIN_DB: prowlarr-main
  PROWLARR_LOG_DB: prowlarr-log

  NGINX_ROBOTS_DISABLE_CRAWLING: |
    location = /robots.txt {
      add_header Content-Type text/plain;
      return 200 "User-agent: *\nDisallow: /\n";
    }

  NGINX_AUTH_URL: |-
    http://ak-outpost-authentik-embedded-outpost.core.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
  NGINX_AUTH_SIGNIN: |-
    https://id.invak.id/outpost.goauthentik.io/start?rd=$scheme%3A%2F%2F$host$escaped_request_uri
  NGINX_AUTH_HEADERS: |-
    Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
  NGINX_AUTH_SNIPPET: |-
    proxy_set_header X-Forwarded-Host $http_host;
