apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: flux-system
data:
  BASE_DOMAIN: invak.id
  NAS_ADDRESS: 100.122.119.95
  PUBLIC_IP: 188.124.94.153
  PRIVATE_IP: 100.75.51.26
  SQUASH_UID: "1024"
