apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster-config.yaml
  - ./gotk-components.yaml
  - ./gotk-sync.yaml
patchesStrategicMerge:
  - ./secrets-sops.yaml
patchesJSON6902:
  - target:
      kind: Deployment
      name: "kustomize-controller"
    patch: &requeue-dependency |-
      - op: add
        path: "/spec/template/spec/containers/0/args/-"
        value: "--requeue-dependency=5s"
  - target:
      kind: Deployment
      name: "helm-controller"
    patch: *requeue-dependency
