---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: ghcr.io/flaresolverr/flaresolverr
      pullPolicy: IfNotPresent
      tag: v3.3.13@sha256:213bb58aa341a0188e64ce2c21e1c5748b167c719828bc61dd904eb0fb1aec63

    env:
      TZ: ${TIMEZONE}
      PUID: ${SQUASH_UID}
      PGID: ${SQUASH_UID}

    service:
      main:
        ports:
          http:
            port: 8191

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${PRIVATE_WHITELIST}
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
        hosts:
          - host: &flaresolverr-host "flaresolverr.lab.${BASE_DOMAIN}"
            paths:
              - path: /

        tls:
          - hosts:
              - *flaresolverr-host
            secretName: letsencrypt-flaresolverr
