apiVersion: batch/v1
kind: CronJob
metadata:
  name: &app recyclarr
  namespace: apps
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          initContainers:
            - name: render-configs
              image: ghcr.io/onedr0p/recyclarr:2.6.1@sha256:cf9c060a5b08aed86b60f057a7f691191e61adcc7983f3597ab399f4705c9488
              env:
                - name: SONARR_BASE_URL
                  value: https://sonarr.lab.${BASE_DOMAIN}
                - name: SONARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: api-key
                      name: sonarr
                - name: RADARR_BASE_URL
                  value: https://radarr.lab.${BASE_DOMAIN}
                - name: RADARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: api-key
                      name: radarr
              command:
                - "/bin/bash"
                - -c
              args:
                - "envsubst < /config/recyclarr.yaml > /shared/recyclarr.yaml"
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: shared
                  mountPath: /shared
          containers:
            - name: sonarrs
              image: ghcr.io/onedr0p/recyclarr:2.6.1@sha256:cf9c060a5b08aed86b60f057a7f691191e61adcc7983f3597ab399f4705c9488
              command:
                - /app/recyclarr
              args:
                - sonarr
                - --config
                - /config/recyclarr.yaml
              volumeMounts:
                - name: shared
                  mountPath: /config/recyclarr.yaml
                  subPath: recyclarr.yaml
                  readOnly: true
            - name: radarrs
              image: ghcr.io/onedr0p/recyclarr:2.6.1@sha256:cf9c060a5b08aed86b60f057a7f691191e61adcc7983f3597ab399f4705c9488
              command:
                - /app/recyclarr
              args:
                - radarr
                - --config
                - /config/recyclarr.yaml
              volumeMounts:
                - name: shared
                  mountPath: /config/recyclarr.yaml
                  subPath: recyclarr.yaml
                  readOnly: true
          volumes:
            - name: config
              configMap:
                name: *app
            - name: shared
              emptyDir: {}
