apiVersion: batch/v1
kind: CronJob
metadata:
  name: &app recyclarr
  namespace: apps
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          initContainers:
            - name: render-configs
              image: ghcr.io/onedr0p/alpine:3.17.3@sha256:999384960b6114496a5e4036e945141c205d064ce23b87326bd3f8d878c5a9d4
              env:
                - name: SONARR_BASE_URL
                  value: https://sonarr.lab.${BASE_DOMAIN}
                - name: SONARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: api-key
                      name: sonarr
                - name: RADARR_BASE_URL
                  value: https://radarr.lab.${BASE_DOMAIN}
                - name: RADARR_4K_BASE_URL
                  value: https://radarr-4k.lab.${BASE_DOMAIN}
                - name: RADARR_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: api-key
                      name: radarr
              command:
                - "/bin/bash"
                - -c
              args:
                - "envsubst < /config/recyclarr.yml > /shared/recyclarr.yml"
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: shared
                  mountPath: /shared
          containers:
            - name: sonarrs
              image: ghcr.io/recyclarr/recyclarr:4.4.1@sha256:825ab392a0f99e8eaa6c0d1468eae83f9dab449eff7456f011a2fbfd82330bf8
              command:
                - /app/recyclarr/recyclarr
              args:
                - sonarr
                - --config
                - /config/recyclarr.yml
              volumeMounts:
                - name: shared
                  mountPath: /config/recyclarr.yml
                  subPath: recyclarr.yml
                  readOnly: true
            - name: radarrs
              image: ghcr.io/recyclarr/recyclarr:4.4.1@sha256:825ab392a0f99e8eaa6c0d1468eae83f9dab449eff7456f011a2fbfd82330bf8
              command:
                - /app/recyclarr/recyclarr
              args:
                - radarr
                - --config
                - /config/recyclarr.yml
              volumeMounts:
                - name: shared
                  mountPath: /config/recyclarr.yml
                  subPath: recyclarr.yml
                  readOnly: true
          volumes:
            - name: config
              configMap:
                name: *app
            - name: shared
              emptyDir: {}
