apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
  namespace: default
spec:
  interval: 10m0s
  chart:
    spec:
      chart: prometheus-operator-crds
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: core
