apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: hajimari
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: apps
      interval: 10m0s
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.3.0@sha256:dfdb8d1b77fbcb22caaa3a11efddff4ac34b410ea3c30253fb0de2464f70c92b
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - apps
      name: "inva"
      lightTheme: "tron"
      darkTheme: "tron"
      globalBookmarks:
        - group: Dev
          bookmarks:
            - name: GitHub
              url: "https://github.com"
        - group: Social
          bookmarks:
            - name: Twitter
              url: "https://twitter.com"
        - group: Media
          bookmarks:
            - name: YouTube
              url: "https://youtube.com"
            - name: Plex
              url: "https://app.plex.tv"
        - group: Communicate
          bookmarks:
            - name: Messenger
              url: "https://facebook.com/messages"
        - group: Cloud
          bookmarks:
            - name: Google Drive
              url: "https://drive.google.com"
            - name: Synology
              url: "https://invakid.quickconnect.to"
        - group: Games
          bookmarks:
            - name: Lichess
              url: "https://lichess.org"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          hajimari.io/enable: "true"
          hajimari.io/icon: "weather-sunset"
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
        hosts:
          - host: &hajimari-host "lab.${BASE_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *hajimari-host
            secretName: "letsencrypt-hajimari"
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
