apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: metallb
      version: "5.0.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
