kind: Endpoints
apiVersion: v1
metadata:
  name: synology-reverse-proxy
  namespace: apps
subsets:
  - addresses:
      - ip: ${NAS_ADDRESS}
    ports:
      - name: dsm
        port: 5000
        protocol: TCP
