kind: EndpointSlice
apiVersion: v1
metadata:
  name: synology-reverse-proxy
  namespace: apps
ports:
  - name: dsm
    port: 5000
    protocol: TCP
endpoints:
  - addresses:
      - ip: ${NAS_ADDRESS}
    conditions:
      ready: true
