apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tor-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
