kind: EndpointSlice
apiVersion: v1
metadata:
  name: router-reverse-proxy
  namespace: apps
addressType: IPv4
ports:
  - name: http
    port: 80
    protocol: TCP
endpoints:
  - addresses:
      - ip: ${ROUTER_IP}
    conditions:
      ready: true
