apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: ghcr.io/onedr0p/prowlarr-nightly
      tag: 1.1.0.2295@sha256:be4bfa0bd62882db780489aecd5e03d9a3199b695c6f12ffcaff10fa5e449ef5

    podAnnotations:
      setGateway: "true"

    podSecurityContext:
      runAsUser: ${SQUASH_UID}
      runAsGroup: ${SQUASH_UID}
      fsGroup: ${SQUASH_UID}
      fsGroupChangePolicy: "OnRootMismatch"

    env:
      TZ: ${TIMEZONE}
      PROWLARR__INSTANCE_NAME: Prowlarr
      PROWLARR__PORT: &port 9696
      PROWLARR__LOG_LEVEL: info
      PROWLARR__ANALYTICS_ENABLED: "False"
      PROWLARR__AUTHENTICATION_METHOD: External
      PROWLARR__POSTGRES_HOST: postgres.core.svc.cluster.local
      PROWLARR__POSTGRES_MAIN_DB: ${PROWLARR_MAIN_DB}
      PROWLARR__POSTGRES_LOG_DB: ${PROWLARR_LOG_DB}
      PROWLARR__POSTGRES_USER: postgres
      PROWLARR__POSTGRES_PASSWORD:
        secretKeyRef:
          name: postgres-creds
          key: postgres-password

    hostname: prowlarr

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${PRIVATE_WHITELIST}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/prowlarr/nord.css"></head>';
            sub_filter_once on;
          cert-manager.io/cluster-issuer: letsencrypt
          hajimari.io/enable: "true"
          hajimari.io/icon: cloud-search
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
        hosts:
          - host: &prowlarr-host "prowlarr.lab.${BASE_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *prowlarr-host
            secretName: letsencrypt-prowlarr

    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config

    resources:
      requests:
        cpu: 20m
        memory: 273M
      limits:
        memory: 1841M
