apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app windmill
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: windmill
      version: 2.0.38
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: windmill
        namespace: apps

  values:
    windmill:
      baseDomain: &windmill-domain windmill.lab.${BASE_DOMAIN}
      databaseUrl: postgres://postgres:${POSTGRES_PASSWORD}@postgres.core.svc.cluster.local/windmill?sslmode=disable
      appReplicas: 1
      lspReplicas: 1
      workerGroups:
        - name: "default"
          replicas: 3
        - name: "native"
          replicas: 1

    postgresql:
      enabled: false

    minio:
      enabled: false

    ingress:
      enabled: true
      className: nginx
      tls:
        - hosts:
            - *windmill-domain
          secretName: letsencrypt-windmill
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: Windmill
        gethomepage.dev/description: "Developer platform to turn scripts into workflows and UIs"
        gethomepage.dev/group: Applications
        gethomepage.dev/icon: webhook.png
        gethomepage.dev/href: "https://windmill.lab.${BASE_DOMAIN}/"
        gethomepage.dev/pod-selector: >-
          app in (
            windmill-app,
            windmill-workers,
            windmill-lsp
          )
        external-dns.alpha.kubernetes.io/target: "${PUBLIC_IP}"

  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: windmill-app
            spec:
              template:
                spec:
                  initContainers:
                    - name: init-db
                      image: ghcr.io/onedr0p/postgres-init:15.5@sha256:70b4c228f2e86de39008a35211c76c1ac6de1dcdf0e908ac09ede6a11e2344e2
                      env:
                        - name: INIT_POSTGRES_HOST
                          value: postgres.core.svc.cluster.local
                        - name: INIT_POSTGRES_SUPER_USER
                          value: postgres
                        - name: INIT_POSTGRES_SUPER_PASS
                          value: ${POSTGRES_PASSWORD}
                        - name: INIT_POSTGRES_USER
                          value: postgres
                        - name: INIT_POSTGRES_PASS
                          value: ${POSTGRES_PASSWORD}
                        - name: INIT_POSTGRES_DBNAME
                          value: *app
