---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app outline
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: outlinewiki/outline
      pullPolicy: IfNotPresent
      tag: 0.71.0@sha256:296e6bf408066129dc98e0867dcc4af10a093ea0d6606e39b97acbdefdc40862

    initContainers:
      init-db:
        image: outlinewiki/outline:0.71.0@sha256:296e6bf408066129dc98e0867dcc4af10a093ea0d6606e39b97acbdefdc40862
        command:
          - "/bin/sh"
          - -c
        args:
          - |
            yarn db:create --env=production-ssl-disabled || true
        envFrom:
          - secretRef:
              name: *app

    service:
      main:
        ports:
          http:
            port: 3000

    env:
      - name: URL
        value: https://notes.lab.${BASE_DOMAIN}

    envFrom:
      - secretRef:
          name: *app

    podAnnotations:
      secret.reloader.stakater.com/reload: *app

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: ${PUBLIC_IP}
          cert-manager.io/cluster-issuer: letsencrypt
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Fast, collaborative, knowledge base
          gethomepage.dev/group: Knowledge
          gethomepage.dev/icon: outline.png
          gethomepage.dev/name: Outline

        hosts:
          - host: &host "notes.lab.${BASE_DOMAIN}"
            paths:
              - path: /

        tls:
          - hosts:
              - *host
            secretName: letsencrypt-outline
