apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &name "reloader"
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: reloader
      version: "1.0.80"
      sourceRef:
        kind: HelmRepository
        name: stakater
  values:
    fullnameOverride: *name
