apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app bazarr
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: ghcr.io/onedr0p/bazarr
      tag: 1.1.2@sha256:52742b56fc14f9ccdcfb4fd38f55655a44d30d570325dcb022d199a0503e1d8a

    podSecurityContext:
      supplementalGroups:
        - 65539

    env:
      TZ: ${TIMEZONE}
      BAZARR_PORT: &port 6767

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/bazarr/nord.css"></head>';
            sub_filter_once on;
          cert-manager.io/cluster-issuer: letsencrypt
          hajimari.io/enable: "true"
          hajimari.io/icon: subtitles-outline
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
        hosts:
          - host: &bazarr-host "bazarr.lab.${BASE_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *bazarr-host
            secretName: letsencrypt-bazarr

    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config

      data:
        enabled: true
        type: nfs
        server: "${NAS_ADDRESS}"
        path: "${TORRENTS_VOLUME}"
        mountPath: /data/nas-torrents

    resources:
      requests:
        cpu: 15m
        memory: 268M
      limits:
        memory: 2357M
