apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app ${APP_NAME}
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: ghcr.io/onedr0p/bazarr
      tag: 1.4.0@sha256:c81c4d9cbec093d5a999cfa3cd1af01d3f00d6292d6f5c33608510cef0ed83c7

    podSecurityContext:
      supplementalGroups:
        - 65539

    env:
      TZ: ${TIMEZONE}
      BAZARR_PORT: &port 6767

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${PRIVATE_WHITELIST}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/bazarr/${THEME}.css"></head>';
            sub_filter_once on;
          cert-manager.io/cluster-issuer: letsencrypt
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: ${INSTANCE_NAME}
          gethomepage.dev/description: Subtitle downloader for Sonarr/Radarr
          gethomepage.dev/group: Media Automation
          gethomepage.dev/icon: bazarr.png
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
        hosts:
          - host: &bazarr-host "${APP_NAME}.lab.${BASE_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *bazarr-host
            secretName: letsencrypt-${APP_NAME}

    persistence:
      config:
        enabled: true
        existingClaim: ${APP_NAME}-config

      data:
        enabled: true
        type: nfs
        server: "${NAS_HOSTNAME}"
        path: "${TORRENTS_VOLUME}"
        mountPath: /data/nas-torrents

    resources:
      requests:
        cpu: 15m
        memory: 268M
      limits:
        memory: 2357M
