apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP_NAME}-config
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
