apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.4.5@sha256:8d3a198a125e08940c0a2615d1885e6111113d19cd727efd2883e78cf734504b

    podAnnotations:
      setGateway: "true"
      configmap.reloader.stakater.com/reload: "qbittorrent-config"

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    hostNetwork: true
    dnsPolicy: "ClusterFirstWithHostNet"

    initContainers:
      copy-config:
        image: busybox:1.35.0@sha256:d7f4aada301c0f13d93ceed62fef318c195c38bf430fc8bfbdf1d850514422ff
        command:
          - "/bin/sh"
          - -c
        args:
          - cp /data/configfiles/* /data/config/
        volumeMounts:
          - name: config
            mountPath: /data/config
          - name: configfiles
            mountPath: /data/configfiles

    dnsConfig:
      options:
        - name: ndots
          value: "1"

    env:
      TZ: ${TIMEZONE}
      UMASK: "022"
      QBITTORRENT__PORT: &port 8080
      QBITTORRENT__USE_PROFILE: "true"

    hostname: qbittorrent

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_hide_header "x-webkit-csp";
            proxy_hide_header "content-security-policy";
            proxy_hide_header "X-Frame-Options";
            proxy_set_header Accept-Encoding "";
            sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/qbittorrent/nord.css"></head>';
            sub_filter_once on;
          cert-manager.io/cluster-issuer: letsencrypt
          hajimari.io/enable: "true"
          hajimari.io/icon: "progress-download"
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
        hosts:
          - host: &qbittorrent-host "qbit.lab.${BASE_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *qbittorrent-host
            secretName: letsencrypt-qbittorrent

    persistence:
      config:
        enabled: true
        type: emptyDir
        mountPath: /config/qBittorrent/config

      cache:
        enabled: true
        type: emptyDir
        mountPath: /config/qBittorrent/cache

      configfiles:
        enabled: true
        type: configMap
        name: qbittorrent-config
        mountPath: "-"

      data:
        enabled: true
        existingClaim: qbittorrent-config
        mountPath: /config/qBittorrent/data

      media:
        enabled: true
        type: nfs
        server: "${NAS_ADDRESS}"
        path: "${TORRENTS_VOLUME}"
        mountPath: /data/nas-torrents

    resources:
      requests:
        cpu: 49m
        memory: 765M
      limits:
        memory: 1426M
