apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.5.0@sha256:fbe9ad5ed471ca085e501f934aeb6fbfb0566d48e366514fa29c665d43c319db

    podAnnotations:
      setGateway: "true"
      configmap.reloader.stakater.com/reload: "qbittorrent-config"

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    hostNetwork: true
    dnsPolicy: "ClusterFirstWithHostNet"

    initContainers:
      copy-config:
        image: busybox:1.35.0@sha256:f4ed5f2163110c26d42741fdc92bd1710e118aed4edb19212548e8ca4e5fca22
        command:
          - "/bin/sh"
          - -c
        args:
          - cp /data/configfiles/* /data/config/
        volumeMounts:
          - name: data
            mountPath: /data/config
            subPath: config
          - name: configfiles
            mountPath: /data/configfiles
      install-vuetorrent:
        image: joshkeegan/zip:3.17.0@sha256:060fd9b5da1cb0fb0db1785945e1b5d583f69f54440b4deb8f6887b1f143eacd
        command:
          - "/bin/sh"
          - -c
        args:
          - |
            # renovate: github-release depName=WDaan/VueTorrent
            VUETORRENT_VERSION="v1.1.0"
            wget "https://github.com/WDaan/VueTorrent/releases/download/$${VUETORRENT_VERSION}/vuetorrent.zip" -O /data/config/vuetorrent.zip
            unzip /data/config/vuetorrent.zip -d /data/config/
        volumeMounts:
          - name: data
            mountPath: /data/config
            subPath: config

    dnsConfig:
      options:
        - name: ndots
          value: "1"

    env:
      TZ: ${TIMEZONE}
      UMASK: "022"
      QBITTORRENT__PORT: &port 8080
      QBITTORRENT__USE_PROFILE: "true"

    hostname: qbittorrent

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${PRIVATE_WHITELIST}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_hide_header "x-webkit-csp";
            proxy_hide_header "content-security-policy";
            proxy_hide_header "X-Frame-Options";
            proxy_set_header Accept-Encoding "";
          nginx.ingress.kubernetes.io/proxy-body-size: 16m
          cert-manager.io/cluster-issuer: letsencrypt
          hajimari.io/enable: "true"
          hajimari.io/icon: "progress-download"
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
        hosts:
          - host: &qbittorrent-host "qbit.lab.${BASE_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *qbittorrent-host
            secretName: letsencrypt-qbittorrent

    persistence:
      cache:
        enabled: true
        type: emptyDir
        mountPath: /config/qBittorrent/cache

      configfiles:
        enabled: true
        type: configMap
        name: qbittorrent-config
        mountPath: "-"

      data:
        enabled: true
        existingClaim: qbittorrent-config
        subPath:
          - path: data
            mountPath: /config/qBittorrent/data
          - path: config
            mountPath: /config/qBittorrent/config

      media:
        enabled: true
        type: nfs
        server: "${NAS_HOSTNAME}"
        path: "${TORRENTS_VOLUME}"
        mountPath: /data/nas-torrents

    resources:
      requests:
        cpu: 49m
        memory: 765M
      limits:
        memory: 1426M
