apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 1.0.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.4.5@sha256:112b2cc60df8035833e2c7a374082e3e1c877b8e7cfd610ae3f1c7a6d65d832d

    podAnnotations:
      setGateway: "true"
      configmap.reloader.stakater.com/reload: "qbittorrent-config"

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    hostNetwork: true
    dnsPolicy: "ClusterFirstWithHostNet"

    initContainers:
      copy-config:
        image: busybox:1.35.0@sha256:e732c9503025a01d747450b09955f8b96211902fe6ea65b28535a546dedbe82d
        command:
          - "/bin/sh"
          - -c
        args:
          - cp /data/configfiles/* /data/config/
        volumeMounts:
          - name: config
            mountPath: /data/config
          - name: configfiles
            mountPath: /data/configfiles
      install-vuetorrent:
        image: joshkeegan/zip:3.16.2@sha256:3310636993bf07850005de2f6b24a0d08437128adcc74c99a4b62fe408ca34aa
        command:
          - "/bin/sh"
          - -c
        args:
          - |
            # renovate: github-release depName=WDaan/VueTorrent
            VUETORRENT_VERSION="v0.19.0"
            wget "https://github.com/WDaan/VueTorrent/releases/download/$${VUETORRENT_VERSION}/vuetorrent.zip" -O /data/config/vuetorrent.zip
            unzip /data/config/vuetorrent.zip -d /data/config/
        volumeMounts:
          - name: config
            mountPath: /data/config

    dnsConfig:
      options:
        - name: ndots
          value: "1"

    env:
      TZ: ${TIMEZONE}
      UMASK: "022"
      QBITTORRENT__PORT: &port 8080
      QBITTORRENT__USE_PROFILE: "true"

    hostname: qbittorrent

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_hide_header "x-webkit-csp";
            proxy_hide_header "content-security-policy";
            proxy_hide_header "X-Frame-Options";
            proxy_set_header Accept-Encoding "";
          cert-manager.io/cluster-issuer: letsencrypt
          hajimari.io/enable: "true"
          hajimari.io/icon: "progress-download"
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
        hosts:
          - host: &qbittorrent-host "qbit.lab.${BASE_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *qbittorrent-host
            secretName: letsencrypt-qbittorrent

    persistence:
      config:
        enabled: true
        type: emptyDir
        mountPath: /config/qBittorrent/config

      cache:
        enabled: true
        type: emptyDir
        mountPath: /config/qBittorrent/cache

      configfiles:
        enabled: true
        type: configMap
        name: qbittorrent-config
        mountPath: "-"

      data:
        enabled: true
        existingClaim: qbittorrent-config
        mountPath: /config/qBittorrent/data

      media:
        enabled: true
        type: nfs
        server: "${NAS_ADDRESS}"
        path: "${TORRENTS_VOLUME}"
        mountPath: /data/nas-torrents

    resources:
      requests:
        cpu: 49m
        memory: 765M
      limits:
        memory: 1426M
