apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.6.3@sha256:44665cefd690411eead93f3c3cefa41e50fddad23b7221ce009bf5e7e66de9dc

    podAnnotations:
      setGateway: "true"
      configmap.reloader.stakater.com/reload: "qbittorrent-config"

    podSecurityContext:
      runAsUser: ${SQUASH_UID}
      runAsGroup: ${SQUASH_UID}
      fsGroup: ${SQUASH_UID}

    initContainers:
      copy-config:
        image: busybox:1.36.1@sha256:650fd573e056b679a5110a70aabeb01e26b76e545ec4b9c70a9523f2dfaf18c6
        command:
          - "/bin/sh"
          - -c
        args:
          - cp /data/configfiles/* /data/config/
        volumeMounts:
          - name: data
            mountPath: /data/config
            subPath: config
          - name: configfiles
            mountPath: /data/configfiles
      install-vuetorrent:
        image: busybox:1.36.1@sha256:650fd573e056b679a5110a70aabeb01e26b76e545ec4b9c70a9523f2dfaf18c6
        command:
          - "/bin/sh"
          - -c
        args:
          - |
            # renovate: github-release depName=WDaan/VueTorrent
            VUETORRENT_VERSION="v2.7.1"
            rm -rf /data/config/vuetorrent
            busybox wget -qO- "https://github.com/WDaan/VueTorrent/releases/download/$${VUETORRENT_VERSION}/vuetorrent.zip" | busybox unzip -d /data/config -
        volumeMounts:
          - name: data
            mountPath: /data/config
            subPath: config

    dnsConfig:
      options:
        - name: ndots
          value: "1"

    env:
      TZ: ${TIMEZONE}
      UMASK: "022"
      QBITTORRENT__PORT: &port 8080
      QBITTORRENT__USE_PROFILE: "true"
      QBITTORRENT__BT_PORT: &bittorrent-port 50413

    hostname: qbittorrent

    service:
      main:
        primary: true
        ports:
          http:
            port: *port

      bittorrent:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: "${QBITTORRENT_IP}"
        ports:
          bittorrent:
            port: *bittorrent-port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: ${PRIVATE_WHITELIST}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_hide_header "x-webkit-csp";
            proxy_hide_header "content-security-policy";
            proxy_hide_header "X-Frame-Options";
            proxy_set_header Accept-Encoding "";
          nginx.ingress.kubernetes.io/proxy-body-size: 16m
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/target: "${PRIVATE_IP}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: qBittorrent
          gethomepage.dev/description: BitTorrent client
          gethomepage.dev/group: Downloads
          gethomepage.dev/icon: qbittorrent.png
        hosts:
          - host: &qbittorrent-host "qbit.lab.${BASE_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *qbittorrent-host
            secretName: letsencrypt-qbittorrent

    persistence:
      cache:
        enabled: true
        type: emptyDir
        mountPath: /config/qBittorrent/cache

      configfiles:
        enabled: true
        type: configMap
        name: qbittorrent-config
        mountPath: "-"

      data:
        enabled: true
        existingClaim: qbittorrent-config
        subPath:
          - path: data
            mountPath: /config/qBittorrent/data
          - path: config
            mountPath: /config/qBittorrent/config

      media:
        enabled: true
        type: nfs
        server: "${NAS_HOSTNAME}"
        path: "${TORRENTS_VOLUME}"
        mountPath: /data/nas-torrents

    resources:
      requests:
        cpu: 49m
        memory: 765M
      limits:
        memory: 1426M
