apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./config-pvc.yaml
  - ./unfinished-pvc.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: qbittorrent-config
    namespace: apps
    files:
      - ./config/categories.json
      - ./config/qBittorrent.conf
generatorOptions:
  disableNameSuffixHash: true
