apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./qbittorrent.yaml
configMapGenerator:
  - name: qbittorrent-config
    namespace: apps
    files:
      - ./config/categories.json
      - ./config/qBittorrent.conf
generatorOptions:
  disableNameSuffixHash: true
