apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-unfinished
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
