default_config:
automation: !include automations.yaml
recorder:
  db_url: postgresql://postgres:${POSTGRES_PASSWORD}@postgres.core.svc.cluster.local/home-assistant?sslmode=disable
homeassistant:
  external_url: https://hass.lab.${BASE_DOMAIN}
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.50.0/24
    - 127.0.0.1
    - 10.42.0.0/16
    - ::1
