apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.0.17"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
  values:
    nfs:
      server: "${NAS_ADDRESS}"
      path: "/volume1/Kubernetes"
