apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reddit-rss
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 1.3.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: ghcr.io/invakid404/reddit-rss
      tag: 2.0.0@sha256:0eaf5199f103efeac5707aaa2d86239d51c85089b0d19954be54a5bc20ed19cb

    env:
      PORT: &port "8080"
      REDDIT_URL: "https://reddit.${BASE_DOMAIN}"

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          external-dns.alpha.kubernetes.io/target: "${PUBLIC_IP}"
        hosts:
          - host: &reddit-rss-host "rss.reddit.${BASE_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *reddit-rss-host
            secretName: letsencrypt-reddit-rss

    resources:
      requests:
        cpu: 50m
        memory: 50M
      limits:
        memory: 100M
