---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: external-dns
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    interval: 2m
    provider: cloudflare
    env:
      - name: CF_API_EMAIL
        valueFrom:
          secretKeyRef:
            name: cloudflare-external-dns-secret
            key: CF_API_EMAIL
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: cloudflare-external-dns-secret
            key: CF_API_KEY
    sources:
      - ingress
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi
