apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: not-used
  namespace: not-used
spec:
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
