---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: libreddit
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: libreddit/libreddit
      pullPolicy: IfNotPresent
      tag: latest@sha256:8efd6e03d837ec3526838429b1190fa14ac23ce71f3711c14e14569a20ac5211

    controller:
      strategy: RollingUpdate

    probes:
      liveness:
        custom: true
        spec:
          httpGet:
            path: /settings
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
      readiness:
        custom: true
        spec:
          httpGet:
            path: /settings
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Libreddit
          gethomepage.dev/description: Private front-end for Reddit
          gethomepage.dev/group: Applications
          gethomepage.dev/icon: libreddit.png
          external-dns.alpha.kubernetes.io/target: "${PUBLIC_IP}"
        hosts:
          - host: &libreddit-host "reddit.${BASE_DOMAIN}"
            paths:
              - path: /

        tls:
          - hosts:
              - *libreddit-host
            secretName: letsencrypt-libreddit
