---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: libreddit
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: spikecodes/libreddit
      pullPolicy: IfNotPresent
      tag: latest@sha256:5c220f7f55b6c4c4ea7c3da4674a10bc957900b384d41d82cef3d6b9d8fc02c1

    controller:
      strategy: RollingUpdate

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          hajimari.io/enable: "true"
          hajimari.io/icon: "reddit"
          external-dns.alpha.kubernetes.io/target: "${PUBLIC_IP}"
        hosts:
          - host: &libreddit-host "reddit.${BASE_DOMAIN}"
            paths:
              - path: /

        tls:
          - hosts:
              - *libreddit-host
            secretName: letsencrypt-libreddit
