---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: libreddit
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 0.1.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps

  values:
    image:
      repository: spikecodes/libreddit
      pullPolicy: IfNotPresent
      tag: latest

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: &libreddit-host "libreddit.lab.invak.id"
            paths:
              - path: /

        tls:
          - hosts:
              - *libreddit-host
            secretName: letsencrypt-libreddit
