apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app prometheus-snmp-exporter-nas
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      version: 1.2.1
      chart: prometheus-snmp-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: apps
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    fullnameOverride: *app
    image:
      repository: quay.io/prometheus/snmp-exporter
    extraArgs:
      - "--config.file=/config/snmp.yaml"
    extraSecretMounts:
      - name: *app
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        secretName: *app
        readOnly: true
        defaultMode: 420
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    serviceMonitor:
      enabled: true
      namespace: apps
      params:
        - name: nas
          module:
            - synology
          target: ${NAS_ADDRESS}
      path: /snmp
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: __param_target
        - sourceLabels: [__param_target]
          targetLabel: instance
        - sourceLabels: [__param_target]
          regex: (.*)
          replacement: ${1}:9116
          targetLabel: __address__
