apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./secret.yaml
configMapGenerator:
  - name: prometheus-snmp-exporter-nas-dashboard
    namespace: apps
    files:
      - ./dashboard.json
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/component: monitoring
generatorOptions:
  disableNameSuffixHash: true
