apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: prometheus-snmp-exporter-nas
    namespace: apps
    files:
      - ./snmp.yaml
generatorOptions:
  disableNameSuffixHash: true
