apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: apps
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps
  interval: 10m0s
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2024.1.1@sha256:c0752d4901483e0116120bc44230af5793d32bd337730e5d06bef2930e289dce

    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-init:16.1@sha256:dda75857689116d9c233ec0978cb905da0f952618dfbe1b8731aa1071044eaf0
        env:
          - name: INIT_POSTGRES_HOST
            value: postgres.core.svc.cluster.local
          - name: INIT_POSTGRES_SUPER_USER
            value: postgres
          - name: INIT_POSTGRES_SUPER_PASS
            value: ${POSTGRES_PASSWORD}
          - name: INIT_POSTGRES_USER
            value: postgres
          - name: INIT_POSTGRES_PASS
            value: ${POSTGRES_PASSWORD}
          - name: INIT_POSTGRES_DBNAME
            value: *app
      install-hacs:
        image: busybox:1.36.1@sha256:ba76950ac9eaa407512c9d859cea48114eeff8a6f12ebaa5d32ce79d4a017dd8
        command:
          - "/bin/sh"
          - -c
        args:
          - |
            # renovate: github-release depName=hacs/integration
            HACS_VERSION="1.33.0"
            mkdir -p /config/custom_components
            rm -rf /config/custom_components/hacs
            busybox wget -qO- "https://github.com/hacs/integration/releases/download/$${HACS_VERSION}/hacs.zip"  | busybox unzip -d /config/custom_components/hacs -
        volumeMounts:
          - name: config
            mountPath: /config
      copy-config:
        image: busybox:latest@sha256:ba76950ac9eaa407512c9d859cea48114eeff8a6f12ebaa5d32ce79d4a017dd8
        command:
          - "/bin/sh"
          - -c
        args:
          - cp /configfiles/* /config/
        volumeMounts:
          - name: config
            mountPath: /config
          - name: configfiles
            mountPath: /configfiles

    hostNetwork: true
    dnsPolicy: "ClusterFirstWithHostNet"
    dnsConfig:
      options:
        - name: ndots
          value: "1"

    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "${PUBLIC_IP}"
          cert-manager.io/cluster-issuer: letsencrypt
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Home Assistant
          gethomepage.dev/description: Open source home automation
          gethomepage.dev/group: Applications
          gethomepage.dev/icon: home-assistant.png
        hosts:
          - host: &hass-host "hass.lab.${BASE_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *hass-host
            secretName: letsencrypt-home-assistant

    podAnnotations:
      configmap.reloader.stakater.com/reload: home-assistant-config

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
      configfiles:
        enabled: true
        type: configMap
        name: home-assistant-config

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
