apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: abcccid-runner
  namespace: apps
spec:
  template:
    spec:
      repository: invakid404/abcccid
      image: ghcr.io/invakid404/runners/abcccid
      dockerMTU: 1400
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: abcccid-runner-autoscaler
  namespace: apps
spec:
  scaleTargetRef:
    name: abcccid-runner
  minReplicas: 0
  maxReplicas: 1
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "30m"
