---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app image-host
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14.10@sha256:71ddc70edccf201d6a521fe6216bc58d8c7c856a1ef96c4d4fbe9f548818ea4d
            env:
              - name: INIT_POSTGRES_HOST
                value: postgres.core.svc.cluster.local
              - name: INIT_POSTGRES_SUPER_USER
                value: postgres
              - name: INIT_POSTGRES_SUPER_PASS
                value: ${POSTGRES_PASSWORD}
              - name: INIT_POSTGRES_USER
                value: postgres
              - name: INIT_POSTGRES_PASS
                value: ${POSTGRES_PASSWORD}
              - name: INIT_POSTGRES_DBNAME
                value: *app

        containers:
          main:
            image:
              repository: ghcr.io/invakid404/image-host
              tag: 1.1.0@sha256:9e4c104a3fb7c9e4532fe4c5dc91cd9ecb4b73a82db4be86c312ad910eed46d9
            envFrom:
              - secretRef:
                  name: *app

        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

    defaultPodOptions:
      imagePullSecrets:
        - name: docker-config

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        className: tailscale
        annotations:
          tailscale.com/funnel: "true"
        hosts:
          - host: &host img.${TAILSCALE_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
