---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app image-host
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.2@sha256:3436dfbbc2799332a01361e007e3b408d016cfc235261e1caccc65e6edadf516
            env:
              - name: INIT_POSTGRES_HOST
                value: postgres.core.svc.cluster.local
              - name: INIT_POSTGRES_SUPER_USER
                value: postgres
              - name: INIT_POSTGRES_SUPER_PASS
                value: ${POSTGRES_PASSWORD}
              - name: INIT_POSTGRES_USER
                value: postgres
              - name: INIT_POSTGRES_PASS
                value: ${POSTGRES_PASSWORD}
              - name: INIT_POSTGRES_DBNAME
                value: *app

        containers:
          main:
            image:
              repository: ghcr.io/invakid404/image-host
              tag: 1.2.2@sha256:58d53131eb36f5c6210ed5fda6cd50ad0cd9c0c2f2b4b53db5fbdc99a17cce6d
            envFrom:
              - secretRef:
                  name: *app

        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

    defaultPodOptions:
      imagePullSecrets:
        - name: docker-config

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        className: tailscale
        annotations:
          tailscale.com/funnel: "true"
        hosts:
          - host: &host img.${TAILSCALE_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
