apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: image-host
    namespace: apps
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:qQ2UjdGUy5S1vuRplWWxNuDxiSb92OAcJkKID1b6KFvavbOY0xeeo9RMZnuzG1KUK6AfUboSGpL6je8D5OquWxkufmE4QJEo5v1jGCj8IgzM8m432CNnoIF4/Kq3PdwCQH5ttdI=,iv:y2GfhepBmYCyy634IQUUkK5mSjP/Bujl1mpD312hjvs=,tag:m8HacUlelsC3TUTuOfsxAA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TwlcD9KdnLPrJ+U2vcFcTunH7PFx7XsDwcU5U9Qq/ug=,iv:GCrRFyB84YUB6XHSIxTye1ud70Sb1KedR7qc61JmQtQ=,tag:ufOCTDYxdbs57YE2UIch8w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uI4ztyGpkwnQKcTuMQQi2xEyzDnalxZSOVMrW1XI9W35p06+NP2FqbKBoQKqRGT0epBLbRqm9+t2c8znTjKEzw==,iv:UW7LdfthBxC2bfiDGC9YsrXc1Z+D0rjrM8d14btLq2M=,tag:gFD41gn7ezOK2DSRR7CQ/w==,type:str]
    AWS_API_URL: ENC[AES256_GCM,data:ctMxzo99hIYkW+rT1LMVqSlkTRPzAB0IiOdJbk4q7X0UuiaQFoUvPRUpwsaf9iFALFo7zeORpTGVVyn63LIn2Xs=,iv:7Uicotm04ozX9IEelaCAdzmeiSR6KyUJ+n5oZ23ZKhw=,tag:kgfWD5eNDdEVIph5oXZmoA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:f0k38g==,iv:E5Bg5UH//SSeRle1RrOg5gaW2nfS05A95wsYBTNpnkU=,tag:po9fxEnDc/qVki4IRMBVYw==,type:str]
    AWS_S3_BUCKET: ENC[AES256_GCM,data:ftwSvWsE,iv:1ygQ3SfOahoapipdVyhPepRzjqKiD9DjRXtL+f8eytk=,tag:UTXZQ9d49t2+itlDvcbLXA==,type:str]
    UPLOAD_SECRET_HEADER: ENC[AES256_GCM,data:vcjYQd6bNXyJd7i64978rqONqRU=,iv:77+A2AbSEDGPs7wfjzAph2bmQ+gr/OQnU4XK3BN+Ie4=,tag:Hn79cqOCvqXfrc/9ppR4HA==,type:str]
    UPLOAD_SECRET_VALUE: ENC[AES256_GCM,data:1u/AzbeZM1gjByelCDwSKSo=,iv:uNEPA759xKgTnc9tl/IJILZiaYObEDAIKj5VpaE8VAM=,tag:UnbK9J+gYx+D1RwEqBKGIw==,type:str]
    LOGGER_FORMAT: ENC[AES256_GCM,data:bphsNXWYg39swYH0Ru0nND9PCTabgwidGt/YJC5SbzkhFCgxFH0hN0wvF3WQBvYU+v+Fd5CMEYPDyTnS+E3Syg==,iv:GksGRVAijKw6S4cXsvRHhvh5fMFlO17dTNgsGU3plBA=,tag:OOzzAPB500Cz2qcACAfBRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-19T18:39:47Z"
    mac: ENC[AES256_GCM,data:2zMVwhKUhbE3UXyBcplPZlqGJcZnvdr0z+CgIrK/+Ks1vgL5rlxEeOZA9+9cuINYuWBvrGcJXkNaBhA6g9EyC1OwFPSkeWARmuExQjqi/YhfvMiZtnn+tebBKkkffT3Rnqw8+amJo5+RA5e4qZCIFBmsK6OD7d19qgBohYsCj4Y=,iv:F3EFwxn7LPV+cgICtB3QTpFciILQ3p/QYShXoGEjR+8=,tag:YkC18+6MZEfNz3zoMCnQRg==,type:str]
    pgp:
        - created_at: "2023-10-17T15:56:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA83EhJxcYAoBAQ/+KgeXcDJt9pki8K2zJTXUtj7WNRZnOm+M2+WumG9QzCOe
            TS+15Tei51hZ0ZJuXDSz9i11K1ktu9gzdP8eRBNj1iIpxP17HnspdRkX/RvlX+b2
            HC2f9zxd2VS+DafVNLKM1kzZAy9qLmobRkQwRHvtf+50ETyQiV22/XkHCRGoSjO2
            H35HnKcHiw+F8T5aPoOrkGCTkAbo5OOUD5eO2IKYz+JogtR+TgxOSAxUpD29kJ8Y
            6I7a7xzSJE72/Lk8kfAB1NzhSVzu9UKGmDXV0i57aJ8U3HN9jqPjeLjGzD3W639P
            JDakVIYu8kxPbV6dyxGE89OOXjMPAT+bUz+AawQJUP5tgaJnMdIVKkIJb72DrK/Y
            4ddefZk0rSMfaLe4HLdeZQYN/sZmxv2ZU8XfCRHupiYogtfLF5Wi2C8oRnDWT28H
            9nQbCOu1UmID+EzgEdwpxUEuN1lMCCz/o2CBqcR+U4m/nB7hQEZj551u3Z/tmBbD
            s8jJBf9HLAMAuFWxJYgqkQGsGZvgvTDzRy3Y412yqDIn2aMBZ0E29bLT/cnlFCZr
            k3L72souU9dBKcrNrsI5RHdJghwL0L+tq1ngiRF2T4DoJPCLMoH5GQY7eLOFWmvy
            nrk4kNrew/kwO/0hcoTJuaclUYurSK5WOe0MXJ0n50NzRShUieCIIOFFnhbNVDTS
            XgF2P5lpEUC2Ztqz5lvl6AhL5/jmX2hT1EFaz4B/DANabckuYdVGMCWfX3fQRjk0
            mOaGSVCRDFWHyXLXf0NW4jBgTs7Irp/6sjHfSbJJvWKTS2GH2CCNeYQBtF7YDvo=
            =k2tM
            -----END PGP MESSAGE-----
          fp: 05FA72D13D58F8D4588BE3FE5606FFB02A5F0984
    encrypted_regex: ((?i)(pass($|word)|claim|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
