---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app esphome
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/esphome/esphome
              tag: latest@sha256:40d3c269cafeebce030e64f58908bfe74cb4a1a81ccc2a23ff78a0a070fe63d7
            env:
              TZ: "${TIMEZONE}"
              ESPHOME_DASHBOARD_USE_PING: true
            command: ["sh"]
            args:
              - "-c"
              - |
                git config --global --add safe.directory '*'
                /entrypoint.sh dashboard /config
            securityContext:
              runAsNonRoot: false
              readOnlyRootFilesystem: false
              privileged: true
              allowPrivilegeEscalation: true
    persistence:
      data:
        enabled: true
        globalMounts:
          - path: /config
        existingClaim: *app
    service:
      main:
        ports:
          http:
            port: 6052
    ingress:
      main:
        enabled: true
        className: tailscale
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: ESPHome
          gethomepage.dev/description: ESP control system
          gethomepage.dev/group: Applications
          gethomepage.dev/icon: esphome.png
        hosts:
          - host: &host esphome.${TAILSCALE_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
