---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app esphome
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: apps
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: docker.io/esphome/esphome
      tag: latest@sha256:ec9cfe20605153335a166c7ffa6dd390f47fa5ec223d773cf75838076ba76cea
    env:
      TZ: "${TIMEZONE}"
      ESPHOME_DASHBOARD_USE_PING: true
    command: ["sh"]
    args:
      - "-c"
      - |
        git config --global --add safe.directory '*'
        /entrypoint.sh dashboard /config
    securityContext:
      runAsNonRoot: false
      readOnlyRootFilesystem: false
      privileged: true
      allowPrivilegeEscalation: true
    persistence:
      data:
        enabled: true
        mountPath: /config
        existingClaim: *app
    service:
      main:
        ports:
          http:
            port: 6052
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "${PUBLIC_IP}"
          cert-manager.io/cluster-issuer: letsencrypt
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: ESPHome
          gethomepage.dev/description: ESP control system
          gethomepage.dev/group: Applications
          gethomepage.dev/icon: esphome.png
          nginx.ingress.kubernetes.io/auth-url: ${NGINX_AUTH_URL}
          nginx.ingress.kubernetes.io/auth-signin: ${NGINX_AUTH_SIGNIN}
          nginx.ingress.kubernetes.io/auth-response-headers: ${NGINX_AUTH_HEADERS}
          nginx.ingress.kubernetes.io/auth-snippet: ${NGINX_AUTH_SNIPPET}
        hosts:
          - host: &host "esphome.lab.${BASE_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: letsencrypt-esphome
