apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: redis
      version: "17.11.6"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10

  values:
    architecture: standalone

    auth:
      enabled: false

    master:
      persistence:
        enabled: true
        existingClaim: redis-data
