apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-csi-retain
