apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: tailscale-operator
    namespace: core
spec:
    interval: 10m0s
    chart:
        spec:
            chart: ./cmd/k8s-operator/deploy/chart
            sourceRef:
                kind: GitRepository
                name: tailscale-operator
    values:
        oauth:
            clientId: k3n9NG2CNTRL
            clientSecret: ENC[AES256_GCM,data:VZTcvb5pkWKXHFRKDvarPTZODOlBNKKYwJB3KOgR40rL8uQCgvDXpO64JIkXxkSyc/5gRSGMOyAyeQ==,iv:Dp434uC155qtnAuZBJcmQ9qcgkLGx9ZI+ZK9PyZDSYw=,tag:d/ALSVxSJKcQRLvafPY/3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-31T17:23:22Z"
    mac: ENC[AES256_GCM,data:5xjvdiLU7g8TK6i7s1moTVS/jnkfcV0UP2Y11wUok7n9yTo4nIoDkqMP9gGtMZmqetZLviN4Zp4i+61NABzhgBvNu6HCNehFevSSAqu5O1Xke4EmPqk8ztb6xo3qeOsfDV4Yth9qX4Wj60dAPc6CpFkC8D3iG8zRPiLC0ejuHKE=,iv:4raEf94pnGRN5xTdRlnIN8NKqLF4Swr8ns26GT7oeKI=,tag:LHht54lpODlaBoeZlzSnCw==,type:str]
    pgp:
        - created_at: "2023-10-31T17:23:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA83EhJxcYAoBAQ/8CZs0uNbE4t6UkQJJWfKfHcypzCBUrdsR0yCEDmImBnnw
            ONXUGZBZXNRPbZWpBU2XE7C4x1lJdrLSMtEmsCeuNj2wLK9qKnk0KwRv3N3aGUw2
            W3uzFJhhyq5SlGK0aznUCGHo6RiZEyM+FpNnMLeMYOKUVBp5Q7Od9fn1BdCnu7zU
            5vzGYnqArm+rmAMfN7rX5OCTenN5cvESf0qyU5Q/mddjZDS6PMYSKTA6bLqOx221
            ffk37gkS43xaxzddKqlVZZM7V9wQjyipoPa3THlcchJZHIdYcb7+ZF/D9c5FZMjS
            wra6UbC9LewIgjbqN6//D4M0xfg1V8vqJsSUfZqtYTf06juO/ayr+jPceDOS4hv6
            JCb+vkB/cGGuGF0oBTN1T9QK6cwf+GbG+xucM51rWksvwelGHhSzxw4kAxGktntT
            58wzTPIacfnotRHUDnVEHQyQsvO/WPu6i4/vRx7u9cPy+tCPciGZ2QTcetEmWTEP
            RWFfDsHX9bDuA74EGBL4dot/TiwvhRXGlpOke83O5Iw63KR+xQjEfpyyGK0WPV2b
            yEDZeQ/FJAVc9QQs+sNMDTMkkgt5QGeLZqikpcdYnbGTZnGTRyAeY0dYhLjYpy0l
            jqtbJvQOlhfWyuUUPcndHxBDnIzy+ZHKyKbxvkbeeqil+pNB1WmJz3J539SZyhPS
            XAE8bKtO0XkBbcMTq9bOLd7yW5gPUk1k5O9LBKE96EXlTtbUYiP0dQYbtHXp+j8x
            ey0R+8HkWP+TwxVUmKor9shgxSC3mIs1XTuWYdk2FDlRLXNcTxd7V4yoQF9N
            =H0Ly
            -----END PGP MESSAGE-----
          fp: 05FA72D13D58F8D4588BE3FE5606FFB02A5F0984
    encrypted_regex: ((?i)(pass($|word)|claim|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
