apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: core
spec:
  interval: 10m0s
  url: https://prometheus-community.github.io/helm-charts
