apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: synology-csi-chart
  namespace: core
spec:
  interval: 10m0s
  url: https://github.com/SynologyOpenSource/synology-csi
  ref:
    branch: main
