apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: core
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: invakid404@riseup.net
    privateKeySecretRef:
      name: letsencrypt-issuer
    solvers:
      - dns01:
          cloudflare:
            email: invakid404@riseup.net
            apiKeySecretRef:
              name: cloudflare-api-key-secret
              key: api-key
