apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: core
spec:
  interval: 10m0s
  chart:
    spec:
      chart: ./deploy/helm
      sourceRef:
        kind: GitRepository
        name: synology-csi-chart
  values:
    storageClasses:
      delete:
        parameters:
          fsType: btrfs
      retain:
        reclaimPolicy: Retain
        parameters:
          fsType: btrfs
